# Generated by Django 5.0.4 on 2024-05-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_owner_alter_event_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participants',
            new_name='member',
        ),
    ]
