# Generated by Django 5.0.4 on 2024-05-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_participants_event_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='member',
            new_name='participants',
        ),
    ]
